[package]
name = "id_8_largest_product_in_a_series"
version = "1.85.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = {path = "../../utils"}
rayon = "1.8.0"  # Use the latest version available